---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sisgp-dev
images:
- name: ghcr.io/srmourasilva/sistema_programa_de_gestao_susep/sgd
  newTag: "latest"

resources:
- ../../base
- configmaps.yml
- secrets.yml
- ingress.yml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: sisgp

configMapGenerator:
- name: web-api-settings
  files:
  - web-api/appsettings.Homolog.json
  - web-api/connectionstrings.Homolog.json
- name: api-gateway-settings
  files:
  - api-gateway/appsettings.Homolog.json
  - api-gateway/ocelot.Homolog.json
- name: web-app-settings
  files:
  - web-app/env.js
...
