---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: web-api-env
  labels:
    app: web-api
stringData:
  ConnectionStrings__DefaultConnection: 'Server=db,1433;Database=programa_gestao;User Id=sa;Password=P1ssw@rd;'
  ldapOptions__Configurations__0__BindPassword: senha
