---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  labels:
    app: web-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: web-api
              topologyKey: kubernetes.io/hostname
      containers:
      - name: web-api
        image: ghcr.io/srmourasilva/sistema_programa_de_gestao_susep/sgd:latest
        imagePullPolicy: IfNotPresent
        workingDir: /app/api/
        command: ["dotnet"]
        args: ["Susep.SISRH.WebApi.dll"]
        env:
        - name: TZ
          value: America/Sao_Paulo
        - name: ASPNETCORE_URLS
          value: http://*:8080
        envFrom:
        - secretRef:
            name: web-api-env
        - configMapRef:
            name: web-api-env
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
#        livenessProbe:
#          failureThreshold: 3
#          httpGet:
#            path: /management/health
#            port: http
#            scheme: HTTP
#          initialDelaySeconds: 120
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 10
#        readinessProbe:
#          failureThreshold: 1
#          httpGet:
#            path: /management/health
#            port: http
#            scheme: HTTP
#          initialDelaySeconds: 120
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 10
#        startupProbe:
#          failureThreshold: 30
#          httpGet:
#            path: /management/health
#            port: http
#            scheme: HTTP
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 10
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: web-api-settings
          mountPath: /app/api/Settings
      volumes:
      - name: web-api-settings
        configMap:
          defaultMode: 0644
          name: web-api-settings
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
  labels:
    app: web-api
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-api
  type: ClusterIP
---
